### ISSUE TITLE
A couple of errors.

### ISSUE THREAD

**Issue by alexanderNG** [ctchanandy/moodle-mod_advmindmap#9]
I want to join the post. A couple of errors.
1. Why do some shows an error that no students. If you go on this link, then you get on any site Moodle, where he also says that there is no information about the error.

2. When you press the "Continue" button, then dumped in general and of course you get to the general menu Bibliokluba.

**Comment by ctchanandy** [comment]
That error message was generated by Moodle. If a page explaining this error exist in the Moodle docs wiki, the link will go to it. Since I did not add any pages in Moodle docs. it is a dead link.
